number1 = int(input("Enter your intenger: "))
number2 = int(input("Enter your intenger: "))
number3 = int(input("Enter your intenger: "))
number4 = int(input("Enter your intenger: "))
number5 = int(input("Enter your intenger: "))

print((number1 + number2) / number3 - number4*number5 + number1**number3 % number2)
print((number5 + number2) / number3 - number4*number5 + number1**number3 % number2)
print((number4 + number2) / number3 - number4*number5 + number1**number3 % number2)
print((number2 + number2) / number3 - number4*number5 + number1**number3 % number2)
print((number3 + number2) / number3 - number4*number5 + number1**number3 % number2)
print((number1 + number5) / number3 - number4*number5 + number1**number3 % number2)
print((number1 + number3) / number3 - number4*number5 + number1**number3 % number2)
print((number1 + number2) / number3 - number5*number5 + number1**number3 % number2)
print((number1 + number2) / number2 - number4*number5 + number1**number3 % number2)
print((number1 + number2) / number5 - number4*number5 + number1**number3 % number2)